# Generated by Django 6.0.6 on 2026-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_razorpay_order_id_bill_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
