# Generated by Django 6.0.6 on 2026-06-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='table_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
    ]
