# Generated by Django 6.0.6 on 2026-06-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafetable',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('BILL_PENDING', 'Bill Pending'), ('CLEANING', 'Cleaning')], default='AVAILABLE', max_length=20),
        ),
    ]
