# Generated by Django 6.0.6 on 2026-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(default='Cafe QR Ordering', max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_footer', models.CharField(default='Thank you! Visit again.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cafe_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
